group/core/urls.py
from core.views import CreateGroupView,\
                       CreateStudentView,\
                       CreateTeacherView,\
                       DeleteStudentView,\
                       DeleteTeacherView, \
                       GroupView,\
                       StudentView,\
                       TeacherView, \
                       UpdateStudentView,\
                       UpdateTeacherView

from django.urls import path


app_name = "core"

urlpatterns = [
    path('group/create/', CreateGroupView.as_view(),
         name='create-group'),
    path('teacher/create/', CreateTeacherView.as_view(),
         name='create-teacher'),
    path('teacher/list/', TeacherView.as_view(),
         name='teacher-list'),
    path('teacher/update/<int:pk>', UpdateTeacherView.as_view(),
         name='update-teacher'),
    path('student/create/', CreateStudentView.as_view(),
         name='create-student'),
    path('student/update/<int:pk>', UpdateStudentView.as_view(),
         name='update-student'),
    path('student/list', StudentView.as_view(), name='students-list'),
    path('student/delete/<int:pk>', DeleteStudentView.as_view(),
         name='delete-student'),
    path('teacher/delete/<int:pk>', DeleteTeacherView.as_view(),
         name='delete-teacher'),
    path('', GroupView.as_view(), name='home'),
]

group/group/urls.py
import debug_toolbar

from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path("", include('core.urls', 'core')),
]

group/core/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


class Teacher(models.Model):
    name = models.CharField(max_length=255, verbose_name='Имя')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия')

    class Meta:
        verbose_name = 'Препод'
        verbose_name_plural = 'Преподы'

    def __str__(self):
        return f"{self.name} {self.last_name}"


class Group(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название')
    teacher = models.ForeignKey(Teacher,
                                on_delete=models.CASCADE,
                                verbose_name='Препод')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return f"{self.name} "


class Student(models.Model):
    name = models.CharField(max_length=255, verbose_name='Имя')
    last_name = models.CharField(max_length=255,
                                 verbose_name='Фамилия',
                                 null=True)
    phone = PhoneNumberField(null=False, default='-')
    age = models.IntegerField(validators=[MinValueValidator(1),
                                          MaxValueValidator(100)],
                              verbose_name='Возраст')
    group = models.ForeignKey(Group,
                              on_delete=models.CASCADE,
                              verbose_name='Группа')

    class Meta:
        verbose_name = 'Студент'
        verbose_name_plural = 'Студенты'

    def __str__(self):
        return f"{self.name}, {self.group}"

group/core/forms.py
from core.models import Group, Student   # Student, Teacher,

from django import forms


# class GroupCreateForm(forms.Form):
#     name = forms.CharField()
#     teacher = forms.ModelChoiceField(
#         queryset=TeacherModel.objects.all(),
#         widget=forms.widgets.RadioSelect()
#     )
#
#     def save(self):
#         track = GroupModel.objects.create(**self.cleaned_data)
#         return track


class GroupCreateForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = '__all__'
        widgets = {
            'teacher': forms.widgets.RadioSelect()
        }


# class StudentCreateForm(forms.Form):
#     name = forms.CharField()
#     age = forms.IntegerField(max_value=80,
#                              min_value=17
#                              )
#     group = forms.ModelChoiceField(queryset=Teacher.objects.all(),
#                                    widget=forms.widgets.CheckboxInput()
#                                    )


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

group/core/views.py
from core.forms import GroupCreateForm, StudentForm
from core.models import Group, Student, Teacher


from django.db.models.aggregates import Avg, Count, Max, Min
from django.urls import reverse_lazy
from django.views.generic import CreateView,\
                                 DeleteView, \
                                 TemplateView,\
                                 UpdateView


class GroupView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        info_about_group = Group.objects.all().select_related().annotate(
            student_count=Count('student'),
            avg_age=Avg('student__age'),
            min_age=Min('student__age'),
            max_age=Max('student__age')
        )
        context = {
            'info_about_group': info_about_group
        }
        return context


class CreateGroupView(CreateView):
    template_name = 'create.html'
    form_class = GroupCreateForm
    success_url = reverse_lazy('core:home')


class StudentView(TemplateView):
    template_name = 'students_list.html'

    def get_context_data(self, **kwargs):
        students = Student.objects.all().select_related()
        context = {
            'students': students
        }
        return context


class UpdateStudentView(UpdateView):
    template_name = 'create.html'
    success_url = reverse_lazy('core:home')
    form_class = StudentForm
    model = Student


class CreateStudentView(CreateView):
    template_name = 'create.html'
    success_url = reverse_lazy('core:home')
    form_class = StudentForm


class DeleteStudentView(DeleteView):
    model = Student
    success_url = reverse_lazy('core:home')

    def get_success_url(self):
        return reverse_lazy('core:home')


class TeacherView(TemplateView):
    template_name = 'teacher_list.html'

    def get_context_data(self, **kwargs):
        teachers = Teacher.objects.all().select_related()
        context = {
            'teachers': teachers
        }
        return context


class CreateTeacherView(CreateView):
    template_name = 'create.html'
    success_url = reverse_lazy('core:home')
    model = Teacher
    fields = '__all__'


class UpdateTeacherView(UpdateView):
    template_name = 'create.html'
    success_url = reverse_lazy('core:home')
    model = Teacher
    fields = '__all__'


class DeleteTeacherView(DeleteView):
    model = Teacher
    success_url = reverse_lazy('core:home')

    def get_success_url(self):
        return reverse_lazy('core:home')

group/core/templates/create.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href='{% static "css/main.css" %}'>
</head>
<body>
    <div class="container-fluid main_section">
        <div class="container  ">
            <div class="row">
                 <form method="POST">{% csrf_token %}
                    {{form}}
                    <button type="submit" class="main_btn">Создать</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

group/core/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Группы</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="../static/css/main.css">
</head>
<body>
    <section class="container-fluid main_section ">
        <div class="container wrapper_table">
            <div class="row">
                <h1 >Список групп</h1>
                <table class="w-100">
                    <tr>
                        <th>Название группы</th>
                        <th>Количество студентов</th>
                        <th>Средний возраст группы</th>
                        <th>Мин возраст</th>
                        <th>Макс возраст</th>
                        <th>Препод</th>
                    </tr>
                     {% for some_info in info_about_group %}
                        <tr>
                             <td>{{some_info.name}}</td>
                            <td>{{ some_info.student_count}}</td>
                            <td>{{ some_info.avg_age|default:"-"}}</td>
                            <td>{{ some_info.min_age|default:"-"}}</td>
                            <td>{{ some_info.max_age|default:"-"}}</td>
                            <td>{{ some_info.teacher }}</td>
                        </tr>
                    {% endfor %}
                </table>
                <div class="col-md-4 wrapper_btn">
                    <a href="{% url 'core:create-group' %}" class="main_btn btn">Добавить Группу</a>
                </div>
                <div class="col-md-4 wrapper_btn">
                    <a href="{% url 'core:create-student' %}" class="main_btn btn">Добавить Студента</a>
                </div>
                <div class="col-md-4 wrapper_btn">
                    <a href="{% url 'core:create-teacher' %}" class="main_btn btn">Добавить Учителя</a>
                </div>
                <div class="col-md-4 wrapper_btn">
                    <a href="{% url 'core:students-list'%}" class="main_btn btn">Список студентов</a>
                </div>
                <div class="col-md-4 wrapper_btn">
                    <a href="{% url 'core:teacher-list'%}" class="main_btn btn">Список переподов</a>
                </div>
            </div>
            </div>

    </section>
</body>
</html>

group/core/templates/students_list.html
{% load static %}


<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href='{% static "css/main.css" %}'>
</head>
<body>
<section class="container-fluid main_section ">
        <div class="container wrapper_table">
            <div class="row">
                <h1>Список студентов</h1>
                <table class="w-100">
                    <tr>
                        <th>№</th>
                        <th>Имя</th>
                        <th>Группа</th>
                        <th>Возраст</th>
                        <th>Телефон</th>
                        <th></th>
                        <th></th>
                    </tr>
                     {% for student in students %}
                        <tr>
                             <td>{{student.name}}</td>
                            <td>{{ student.last_name}}</td>
                            <td>{{ student.group}}</td>
                            <td>{{ student.age}}</td>
                            <td>{{ student.phone|default:'-'}}</td>
                            <td class="wrapper_btn"><a href="{% url 'core:update-student' student.id %}" class="main_btn btn">Изменить</a></td>
                            <td>
                                <form method="POST" action="{% url 'core:delete-student' student.id %}" class="">
                                    {% csrf_token %}<input type="submit" value="Удалить" class="main_btn">
                                 </form>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
            </div>

    </section>
</body>
</html>

group/core/templates/teacher_list.html
{% load static %}


<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href='{% static "css/main.css" %}'>
</head>
<body>
<section class="container-fluid main_section ">
        <div class="container wrapper_table">
            <div class="row">
                <h1>Список преподов</h1>
                <table class="w-100">
                    <tr>
                        <th>Имя</th>
                        <th>Фамилия</th>
                        <th></th>
                        <th></th>
                    </tr>
                     {% for teacher in  teachers %}
                        <tr>
                             <td>{{ teacher.name }}</td>
                            <td>{{ teacher.last_name}}</td>
                            <td class="wrapper_btn"><a href="{% url 'core:update-teacher' teacher.id %}" class="main_btn btn">Изменить</a></td>
                            <td>
                                <form method="POST" action="{% url 'core:delete-teacher' teacher.id %}" class="">
                                    {% csrf_token %}<input type="submit" value="Удалить" class="main_btn">
                                 </form>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
            </div>

    </section>
</body>
</html>